codecov: true
language: julia
julia:
  - 1.5.2
  - nightly
script:
  - julia -e 'using Pkg; Pkg.build(; verbose=true); Pkg.test(coverage=true)';
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
services:
  - docker
before_install:
  - docker build -t "vpetukhov/baysor:$TRAVIS_BRANCH" ./docker
deploy:
  provider: script
  script:
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin && docker push vpetukhov/baysor
  on:
    branch: master
    tags: true
    julia: 1.5.2
env:
  global:
    - secure: CVl14xmKuHM4q5pPsl0yYuyyrSnX/JmHQW4lrXptP5KoE/owY15kDs3udDtK6zC3eB/WqEeMzUZ9DrigDtCrKo77nOwC9uM8XZYxkIG83LmSfk3aMpvWfxxYzKo3ZSEyyFekAzma0M4Wxu2tH42FcktOLMlPcJI2uoG7Dsn/iq/FeG2+AGF61Ha8iINaFNYczzCq7252HN+N4LlYVUPUtiI7Ea0iLCzP1EwNTkM7j7R9Q8/8wOjNKZ+1ZFq/twKIXlleaOv3wPzK4FErOECfe8jyeW4tNoA9srsB3bckdRM5Rm/q69Ykot77ZJVdUZBg1Eef6QaEgqdk8r8aBdwGxxgrUUTkYG5QNGdbnMquFidB2VkqTc05Zi8+3wJvcJri3TRpLTF09Rlbzz2GTMfGlmHoC7mb0RaFMgOR6w20Mqqvca86gMt0vWU+dQ4kpBxZLr+rlFtVOT8MI3CHlAEk3w7CtdIArHzhp6OrDxfMni+Zb3xetp+pf1DcszT15IuH+De1LzeFjtPDJ3UkbbkG6dIG8hXvTOPmWcigpfctDT8zdVzGGszxKBItBSCtgaU0ZnBdXhdxMtnucJxD3f4Qg2b+KdF//0j4AT7JoSH+OiLxa/vdd7BwNIFC2Xr4GCpIYqbLFrVG5VhXn0SVFRohtJZ8ZPrJGbqVqP7y8Cs67sM=
    - secure: YhXFUT9J1LRanylveSrhGSIET97nvjli9Lmb0HvbvdP24hBe8ZCUDXYKX1cnkS8ex750AU8qC4/vVU2Kl/uj454UmR3Fg9RERWYZvL4HmYE0fDgXBPksxmDvm4M+Ih/U6fkHq3GVw5/EwkQByBfqkGBQ0TtLFpf51GhAUnmMCckyOChAGl+JXO3p0BuYFpgB3+eGMaEdOTmeulxNDSe528WQsCuO4+RmsrqcjEzs62D+D9stlRdR6vG449FUeC46bDhEK5CEfpuAIUtXxozgoyq6hIfVRbuaVYLirQO6kBxjfq5lOhirem2nlW1x07XsUQBfGtbJR7gRsKskn55Se04Pd4moAjT8zAPo5mZbA85gFNgsqpaCmBqSCMLHNSTSH/pUyZAiChhNMxs3EUMytv8SxnbQexLIojIEr7b7feGMPq8ZvIm39l4cZbuHq8ojlUeGDNzob6tephnf1jmO7HYJXDgsUfwwmx6ayEoTeeBNL/eKFf+1XxDt+nVY+gbxU1kNAj5/vcKaevRHA2I1/2erUBRJTtIEkyljdaJHZsGnvdT1Zg/IbUMdOvAFoaE5JHZAC7H6bAtyzdpx0+Tj73nya9K+YmKm/xOiBXeokSpL/HWYUE6rWCtGEzUQlQnHHp8pswXrwMGCKzkBD6pqxYvlMKtbO1Za2o5TUeXB630=
